Algoritmo "Exercício 2"
// Disciplina  : [Noções Básicas de Programação]
// Professor   : Sergio Netto
// Descrição   : Leitura do IMC
// Autor(a)    : Drielle Santos Monteiro
// Data atual  : 08/03/2021
Var
// Seção de Declarações das variáveis 
 peso,alt,IMC: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("peso:")
 leia(peso)
 escreva("altura:")
 leia(alt)
 imc<- peso/(alt*alt)
 escreval("IMC:",imc)

Fimalgoritmo